spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/om
    username: om
    password: database_password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    xyz: TRACE
    xyz.hyffer.onemessage_server.client_api.service.cs_api.ClientRequestBodyDeserializer: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        transaction:
          interceptor: TRACE

om:
  allowed-origins: "*"  # Allowed origins for browser client
  auth:
    username: webapp_username
    password: webapp_password
