spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/omtest
    username: omtest
    password: omtest
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false

logging:
  level:
    xyz: TRACE
    xyz.hyffer.onemessage_server.client_api.service.cs_api.ClientRequestBodyDeserializer: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        transaction:
          interceptor: TRACE
        test:
          context:
            transaction: DEBUG

om:
  allowed-origins: "*"  # Allowed origins for browser client
  auth:
    username: omtest
    password: omtest
